spring:
  datasource:
    url: jdbc:mysql://192.168.0.221:3306/paladin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池配置
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.0.221:3306/paladin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123456
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 86430000
      #      connection-test-query:
      #      minimum-idle:
      maximum-pool-size: 10
      #      metric-registry:
      #      health-check-registry:
      pool-name: paladin-pool
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 192.168.0.221
    port: 6379
    timeout: 0
    password:
  application:
    name: account
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#  mail:
#    protocol: smtp
#    host: smtp.xxx.com
#    port: 25
#    username:
#    password:
logging:
  level:
    root: trace
    com.paladin.account: trace
#pagehelper:
##  自动监测，可以不设置
#  dialect-alias: mysql=com.github.pagehelper.dialect.helper.MySqlDialect
#  auto-dialect: true
#  offset-as-page-num: false
#  row-bounds-with-count: false
#  auto-runtime-dialect: false
#  close-conn: true
#  default-count: true
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  page-size-zero: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-delete-value: 0
      logic-not-delete-value: 1
#eureka:
#  client:
#    fetch-registry: false
server:
  port: 8081
