spring:
  datasource:
    url: jdbc:mysql://192.168.124.221:3306/paladin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接等待超时时间
      max-wait: 60000
      #配置隔多久进行一次检测(检测可以关闭的空闲连接)
      time-between-eviction-runs-millis: 60000
      #配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
#      validation-query-timeout:
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
#      max-open-prepared-statements:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      name:
#      exception-sorter:
#      exception-sorter-class-name:
#      log-abandoned:
#      remove-abandoned:
#      remove-abandoned-timeout:
#      access-to-underlying-connection-allowed:
#      phy-timeout-millis:
#      default-auto-commit:
#      default-read-only:
#      default-transaction-isolation:
#      default-catalog:
#      num-tests-per-eviction-run:
#      max-idle:
#    initConnectionSqls
#    init
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 192.168.124.221
    port: 6379
    timeout: 0
    password:

#  mail:
#    protocol: smtp
#    host: smtp.xxx.com
#    port: 25
#    username:
#    password:

logging:
  level:
   com.paladin.account: DEBUG
pagehelper:
#  自动监测，可以不设置
  dialect-alias: mysql=com.github.pagehelper.dialect.helper.MySqlDialect
  auto-dialect: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
